import {loadIdentityEnvironment} from './helpers/identity-environment.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
function setup(){const window={};loadIdentityEnvironment(window);vm.runInNewContext(fs.readFileSync('prototype/009-2-membership.js','utf8'),{window});const s=window.EvaMembership.create({actorId:'a',people:[{id:'a',name:'甲'},{id:'b',name:'乙'}],clones:[{id:'ai',ownerId:'a',name:'分身'}]});s.createProject('p','项目','a',['ai']);s.addMember('p','a','b');s.createProject('q','其他项目','a',[]);return s;}
test('项目自定义角色仅管理员维护且不授予管理权限',()=>{const s=setup();assert.equal(typeof s.saveProjectRole,'function');const role=s.saveProjectRole('p','a',{name:'CEO',description:'项目决策'});s.setMemberRoles('p','a','b',[role.id]);assert.equal(s.memberRoles('p','b')[0].name,'CEO');assert.equal(s.manager('p','b'),false);assert.throws(()=>s.saveProjectRole('p','b',{name:'前端'}));assert.throws(()=>s.setMemberRoles('q','a','a',[role.id]));assert.throws(()=>s.saveProjectRole('p','a',{name:' CEO '}));});
test('角色多选、AI分配与历史下达快照保持独立',()=>{const s=setup();const product=s.saveProjectRole('p','a',{name:'产品'}),dev=s.saveProjectRole('p','a',{name:'前端'});s.setMemberRoles('p','a','a',[product.id,dev.id]);s.setMemberRoles('p','a','ai',[dev.id]);assert.equal(s.memberRoles('p','ai')[0].name,'前端');const issued=s.taskIssuer('p','a',product.id);s.saveProjectRole('p','a',{id:product.id,name:'产品设计'});assert.equal(issued.issuer_role_name,'产品');assert.equal(s.memberRoles('p','a')[0].name,'产品设计');assert.throws(()=>s.taskIssuer('p','b',dev.id));assert.equal(s.taskIssuer('p','b').issuer_role_name,null);});
test('删除角色清理分配，移除成员重新加入不恢复分工',()=>{const s=setup();const r=s.saveProjectRole('p','a',{name:'HR'});s.setMemberRoles('p','a','b',[r.id]);s.remove('p','a','b');s.addMember('p','a','b');assert.equal(s.memberRoles('p','b').length,0);s.setMemberRoles('p','a','a',[r.id]);s.deleteProjectRole('p','a',r.id);assert.equal(s.memberRoles('p','a').length,0);assert.throws(()=>s.taskIssuer('p','a',r.id));});
test('分身移除后重新加入不恢复项目角色',()=>{const s=setup();const r=s.saveProjectRole('p','a',{name:'前端'});s.setMemberRoles('p','a','ai',[r.id]);s.removeClone('p','a','ai');s.addClone('p','a','ai');assert.equal(s.memberRoles('p','ai').length,0);});
