import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
function setup(){const window={};vm.runInNewContext(fs.readFileSync(new URL('../prototype/009-2-membership.js',import.meta.url),'utf8'),{window});return window.EvaMembership.create({people:[{id:'a',name:'甲',active:true},{id:'b',name:'乙',active:true},{id:'c',name:'丙',active:true},{id:'inactive',active:false}],clones:[{id:'aa',ownerId:'a',name:'甲分身'},{id:'bb',ownerId:'b',name:'乙分身'}]});}
test('创建项目与接受邀请同步全员群；分身不能代选',()=>{const s=setup();s.createProject('p','项目','a',['aa']);assert.equal(s.members('p').length,2);assert.equal(s.groupMembers('all:p').length,2);const i=s.invite('p','a','b');assert.equal(i.status,'pending_accept');assert.throws(()=>s.accept(i.id,'b',['aa']));assert.equal(s.members('p').length,2);s.accept(i.id,'b',['bb']);assert.equal(s.members('p').length,4);assert.equal(s.groupMembers('all:p').length,4);});
test('普通成员邀请先审批且不能重复；接受前无访问权限',()=>{const s=setup();s.createProject('p','项目','a',[]);s.accept(s.invite('p','a','b').id,'b',[]);const i=s.invite('p','b','c');assert.equal(i.status,'pending_approval');assert.equal(s.invite('p','b','c').id,i.id);assert.throws(()=>s.accept(i.id,'c',[]));assert.equal(s.canRead('p','c'),false);s.approve(i.id,'a');s.accept(i.id,'c',[]);assert.equal(s.canRead('p','c'),true);});
test('普通群独立加入，管理员未加入也不可读；子区继承群',()=>{const s=setup();s.createProject('p','项目','a',[]);s.accept(s.invite('p','a','b').id,'b',['bb']);s.createGroup('g','小群','p','b',['bb']);assert.equal(s.canRead('g','a'),false);s.createThread('t','g');assert.equal(s.canRead('t','a'),false);assert.equal(s.canRead('t','bb'),true);assert.throws(()=>s.invite('t','b','a'));assert.throws(()=>s.addClone('g','a','bb'));});
test('移除人类级联移除分身和普通群关系；全员群不能独立修改',()=>{const s=setup();s.createProject('p','项目','a',[]);s.accept(s.invite('p','a','b').id,'b',['bb']);s.createGroup('g','小群','p','a',[]);s.accept(s.invite('g','a','b').id,'b',[]);s.addClone('g','b','bb');assert.throws(()=>s.remove('all:p','a','b'));s.remove('p','a','b');assert.equal(s.canRead('g','bb'),false);assert.equal(s.canRead('p','b'),false);s.accept(s.invite('p','a','b').id,'b',[]);assert.equal(s.canRead('g','b'),false);assert.equal(s.canRead('p','bb'),false);});
test('负责人和群主退出前必须转让；无其他人类时解散普通群',()=>{const s=setup();s.createProject('p','项目','a',[]);assert.throws(()=>s.remove('p','a','a'));s.accept(s.invite('p','a','b').id,'b',[]);s.transfer('p','a','b');s.remove('p','a','a');assert.equal(s.canRead('p','a'),false);s.createGroup('g','小群','p','b',[]);assert.throws(()=>s.remove('g','b','b'));s.dissolveGroup('g','b');assert.equal(s.canRead('g','b'),false);});
test('演示身份只允许已激活人类，重复接受不恢复已移除的成员',()=>{const s=setup();s.setActor('b');assert.equal(s.snapshot().actorId,'b');assert.throws(()=>s.setActor('bb'));s.createProject('p','项目','a',[]);const i=s.invite('p','a','b');s.accept(i.id,'b',[]);s.accept(i.id,'b',[]);s.remove('p','a','b');s.accept(i.id,'b',[]);assert.equal(s.canRead('p','b'),false);});

test('现有通讯录的 AI 条目不进入人类候选人或演示身份',()=>{const window={__EVA_MEMBERSHIP_CLONES:[],localStorage:{getItem:()=>null,setItem:()=>{}}};vm.runInNewContext(fs.readFileSync(new URL('../prototype/009-2-membership.js',import.meta.url),'utf8'),{window});const s=window.EvaMembership.bootstrap([{uid:'u-wangyilin',name:'王宜林'},{uid:'u-b',name:'乙'},{uid:'b-b',name:'分身',ai:true},{uid:'x-b',name:'专家',ai:true}],[{id:'p',name:'项目',members:[]}],{});assert.equal(s.snapshot().people.length,2);assert.equal(s.candidates('p','u-wangyilin').length,1);assert.throws(()=>s.setActor('b-b'));});
test('项目群列表派生唯一全员群，普通群按成员访问且人数实时同步',()=>{const s=setup();s.createProject('p','项目','a',['aa']);s.createGroup('g','普通群','p','a',[]);s.accept(s.invite('p','a','b').id,'b',['bb']);assert.equal(s.channels('p','b',[]).length,1);assert.equal(s.channels('p','b',[])[0].id,'all:p');assert.equal(s.channels('p','b',[])[0].humanCount,2);assert.equal(s.channels('p','b',[])[0].cloneCount,2);assert.equal(s.channels('p','c',[]).length,0);s.accept(s.invite('g','a','b').id,'b',[]);assert.equal(s.channels('p','b',[]).length,2);s.remove('p','a','b');assert.equal(s.channels('p','a',[])[0].humanCount,1);assert.equal(s.channels('p','b',[]).length,0);});
test('移除项目成员须一次性指定其群主接任者；独自所在群自动解散',()=>{const s=setup();s.createProject('p','项目','a',[]);s.accept(s.invite('p','a','b').id,'b',['bb']);s.accept(s.invite('p','a','c').id,'c',[]);s.createGroup('g','工作群','p','b',[]);s.accept(s.invite('g','b','c').id,'c',[]);s.createGroup('solo','个人工作群','p','b',[]);assert.throws(()=>s.remove('p','a','b'));assert.equal(s.canRead('p','b'),true);s.remove('p','a','b',{g:'c'});assert.equal(s.snapshot().groups.g.ownerId,'c');assert.equal(s.snapshot().groups.solo,undefined);assert.equal(s.canRead('g','b'),false);});
test('非项目群按本人加入范围显示，消息和子区历史在重新进入后保留',()=>{const s=setup();s.createGroup('g','非项目群',null,'a',[]);assert.equal(s.channels(null,'b').length,0);s.accept(s.invite('g','a','b').id,'b',['bb']);s.createThread('t','g',{name:'子区',status:1},'a');s.sendMessage('t','b','已收到');assert.equal(s.messagesFor('t','a')[0].text,'已收到');s.remove('g','a','b');assert.equal(s.messagesFor('t','b').length,0);assert.equal(s.messagesFor('t','a').length,1);assert.equal(s.channels(null,'a')[0].threads[0].name,'子区');assert.deepEqual(Array.from(s.mentionCandidates('g').map(p=>p.id)),['a']);});
test('@全体成员只记录人类通知目标；删除子区后不可再读取',()=>{const s=setup();s.createProject('p','项目','a',['aa']);s.createThread('t','all:p',{name:'子区'},'a');s.sendMessage('t','a','@全体成员 请确认');assert.deepEqual(Array.from(s.messagesFor('t','a')[0].notifiedHumanIds),['a']);s.updateThread('t',{deleted:true},'a');assert.equal(s.canRead('t','a'),false);assert.equal(s.messagesFor('t','a').length,0);});

test('分身空选不阻止创建项目、建群及接受邀请',()=>{const s=setup();s.createProject('p','项目','a',[]);s.accept(s.invite('p','a','b').id,'b',[]);s.createGroup('g','项目群','p','a',[]);s.accept(s.invite('g','a','b').id,'b',[]);s.createGroup('o','非项目群',null,'a',[]);s.accept(s.invite('o','a','b').id,'b',[]);for(const id of ['p','g','o']){assert.equal(s.canRead(id,'b'),true);assert.equal(s.members(id).filter(p=>p.kind==='clone').length,0);}assert.equal(s.groupMembers('all:p').length,2);});

test('批量邀请整体校验，失败不创建群或留下部分邀请',()=>{const s=setup();s.createProject('p','项目','a',[]);s.accept(s.invite('p','a','b').id,'b',[]);const before=JSON.stringify(s.snapshot());assert.throws(()=>s.transaction(t=>{t.createGroup('g','群','p','a',[]);t.invite('g','a','b');t.invite('g','a','c');}));assert.equal(JSON.stringify(s.snapshot()),before);s.transaction(t=>{t.createGroup('g','群','p','a',[]);t.invite('g','a','b');});assert.equal(s.canRead('g','b'),false);assert.equal(s.snapshot().invitations.filter(i=>i.scopeId==='g').length,1);});

test('群设置只允许已加入的群主或继承管理员修改，分身不能治理',()=>{const s=setup();s.createProject('p','项目','a',['aa']);s.accept(s.invite('p','a','b').id,'b',[]);s.setAdmin('p','a','b',true);s.createGroup('g','群','p','a',[]);assert.throws(()=>s.setChatSettings('g','b',{notice:'不应写入'}));assert.throws(()=>s.setChatSettings('g','aa',{notice:'不应写入'}));s.accept(s.invite('g','a','b').id,'b',[]);s.setChatSettings('g','b',{name:'整改群',notice:'新公告'});assert.equal(s.snapshot().groups.g.name,'整改群');assert.equal(s.chatSettings('g').notice,'新公告');assert.throws(()=>s.setChatSettings('g','a',{name:' '}));assert.throws(()=>s.setChatSettings('g','a',{notice:'字'.repeat(401)}));});
test('私聊设置与清空记录按人类和会话隔离，不删除其他人的消息',()=>{const s=setup();s.setChatPreferences('dm-b','a',{mute:true,top:true,clearedCount:2});assert.equal(s.chatPreferences('dm-b','a').mute,true);assert.equal(s.chatPreferences('dm-b','b').mute,undefined);assert.equal(s.chatPreferences('dm-c','a').mute,undefined);assert.equal(s.visibleMessages('dm-b','a',[1,2,3]).join(','),'3');assert.equal(s.visibleMessages('dm-b','b',[1,2,3]).length,3);const restored=windowlessRestore(s.snapshot());assert.equal(restored.chatPreferences('dm-b','a').top,true);});
function windowlessRestore(seed){const window={};vm.runInNewContext(fs.readFileSync(new URL('../prototype/009-2-membership.js',import.meta.url),'utf8'),{window});return window.EvaMembership.create(seed);}
